#!/bin/bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

if fish 2>/dev/null; then
        exit
else
        echo "fish failed to start, falling back to bash."
fi
