#!/bin/zsh

export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

typeset -fuz zkbd
typeset -U path PATH manpath sudo_path
typeset -xT SUDO_PATH sudo_path

path=(
        $HOME/bin(N-/)
        $HOME/.local/bin(N-/)
        $HOME/go/bin(N-/)
        $HOME/.cargo/bin(N-/)
        $HOME/.rustup/toolchains/*/bin(N-/)
        $HOME/.deno/bin(N-/)
        $HOME/.ghcup/bin(N-/)
        $HOME/.cabal/bin(N-/)
        $XDG_DATA_HOME/nvim/bin(N-/)
        $path # $PATHと違って:区切りではない
)
export PATH

# MacOSではhomebrewのパスを追加する
if [ "$(uname)" = 'Darwin' ]; then
        export PATH="/opt/homebrew/bin:${PATH}"
fi

if which nvim &> /dev/null; then
        export EDITOR='nvim'
        export MANPAGER='nvim +Man!'
else
        export EDITOR='vim'
        export MANPAGER='vim +MANPAGER --not-a-term -'
fi
export SYSTEMD_EDITOR=$EDITOR

export LESSCHARSET='utf-8'
export LANG='ja_JP.utf8'

export ZENO_ENABLE_SOCK=1
export ZENO_GIT_CAT="bat --color-always"
export ZENO_GIT_TREE="exa --tree"
export ZENO_HOME="$XDG_CONFIG_HOME/zeno"
