#!/usr/bin/env -S bash
set -euo pipefail

file="$1"

preview_file () {
  type="$(file --brief --dereference --mime -- "$file")"
  if [[ "$type" =~ charset=(.*-ascii|utf-8) ]]; then
    bat \
      --style="${BAT_STYLE:-numbers}" \
      --color=always \
      --pager=never \
      --highlight-line=0 \
      -- "$file"
  else
    echo "$type"
  fi
}

preview_directory () {
  eza "$file" \
    --icons \
    --git \
    --time-style relative \
    --all \
    --long \
    --color=always
}

if [ -f "$file"  ]; then
  preview_file
elif [ -d "$file" ]; then
  preview_directory
fi

