return {
  params = {
    priority = {
      'Keyword',
      'Snippet',
      'Variable',
      'Field',
      'Property',
      'Method',
      'Function',
      'Constructor',
      'Class',
      'Interface',
      'Module',
      'Unit',
      'Value',
      'Enum',
      'Color',
      'File',
      'Reference',
      'Folder',
      'EnumMember',
      'Constant',
      'Struct',
      'Event',
      'Operator',
      'TypeParameter',
      'Text',
    },
  },
}
