local home = vim.fn.expand '$HOME/doc/zettelkasten'

require('telekasten').setup {
  home = home,
  take_over_my_home = true,
  auto_set_filetype = true,
  dailies = ('%s/dailies'):format(home),
  weeklies = ('%s/weeklies'):format(home),
  templates = ('%s/templates'):format(home),
  image_subdir = 'img',
  extension = '.md',
  new_note_filename = 'uuid-title',
  uuid_type = '%Y%m%d%H%M',
  uuid_sep = '-',
  follow_creates_nonexisting = true,
  dailies_create_nonexisting = true,
  weeklies_create_nonexisting = true,
  journal_auto_open = false,
  template_new_note = ('%s/templates/new_note.md'):format(home),
  template_new_daily = ('%s/templates/daily.md'):format(home),
  template_new_weekly = ('%s/templates/weekly.md'):format(home),
  image_link_style = 'markdown',
  sort = 'modified',
  plug_into_calendar = true,
  calendar_opts = {
    weeknm = 4,
    calendar_monday = 0,
    calendar_mark = 'left-fit',
  },
  close_after_yanking = false,
  insert_after_inserting = true,
  tag_notation = '#tag',
  command_palette_theme = 'ivy',
  show_tags_theme = 'ivy',
  subdirs_in_links = true,
  template_handling = 'smart',
  new_note_location = 'smart',
  rename_update_links = true,
  follow_url_fallback = nil,
}
